# ~ startup ~
after-login-command = []

after-startup-command = [
    'exec-and-forget borders',
    'exec-and-forget sketchybar',
]

exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 300
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
# on-focus-changed = ['move-mouse window-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 15
outer.bottom = 15
outer.top = 20
outer.right = 15

# ~ set floating windows (apps) ~
[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'preview'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'quicktime player'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'homerow'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'messages'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'calendar'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'music'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'weather'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'replacicon'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'colorslurp'
run = 'layout floating'

# ~ set floating windows (sub-windows) ~
[[on-window-detected]]
if.window-title-regex-substring = 'settings'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = 'preferences'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = 'picture-in-picture'
run = 'layout floating'

# ~ main mode ~
[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -30'
alt-equal = 'resize smart +30'
alt-shift-minus = 'resize smart-opposite -30'
alt-shift-equal = 'resize smart-opposite +30'

alt-ctrl-h = 'resize width -50'
alt-ctrl-j = 'resize height +50'
alt-ctrl-k = 'resize height -50'
alt-ctrl-l = 'resize width +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'

alt-o = 'exec-and-forget open -a /Applications/Obsidian.app'
alt-g = 'exec-and-forget open -a /Applications/Ghostty.app'
alt-enter = 'exec-and-forget open -n /Applications/Ghostty.app'
alt-m = 'exec-and-forget open -a /Applications/Max.app'
#alt-b = 'exec-and-forget open -a /Applications/Opera.app'
alt-z = 'exec-and-forget open -a /Applications/Zen.app'
alt-backslash = 'exec-and-forget open -a /Applications/ChatGPT.app'
alt-f = 'exec-and-forget open -a Finder'

alt-tab = 'workspace-back-and-forth'
alt-x = 'close'
#alt-q = 'exec-and-forget osascript -e "tell application \"app\" to quit"'

# ~ service mode ~
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
space = ['exec-and-forget paper', 'mode main']
s = ['exec-and-forget sketchybar --reload', 'mode main']
w = ['exec-and-forget ~/.local/scripts/applesauce/wp_browse.scpt', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
