## general
set-option -g  prefix                ^X
set-option -g  base-index            1
set-option -g  renumber-windows      on
set-option -g  mouse                 on
set-option -g  history-limit         5000
set-option -g  default-terminal      "tmux-256color"
set-option -ga terminal-overrides    ",*:RGB"
set-option -g  set-clipboard         on
set-option -g  allow-passthrough     on
set-option -g  set-clipboard         external
set-option -g  repeat-time           500
set-option -g  clock-mode-style      12
set-option -g  pane-base-index       1
set-window-option -g pane-base-index 1

## copy mode
set-window-option -g mode-keys vi
bind-key ^u copy-mode
bind-key -T copy-mode-vi  y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi  v send-keys -X begin-selection
bind-key -T copy-mode-vi  i send-keys -X cancel
bind-key -T copy-mode-vi  x send-keys -X copy-line-and-cancel
bind-key -T copy-mode-vi ^v send-keys -X rectangle-toggle

## binds
bind-key h      select-pane -L
bind-key j      select-pane -D
bind-key k      select-pane -U
bind-key l      select-pane -R

bind-key ^j     split-window -v -c "#{pane_current_path}"
bind-key ^k     split-window -v -c "#{pane_current_path}"
bind-key ^h     split-window -h -c "#{pane_current_path}"
bind-key ^l     split-window -h -c "#{pane_current_path}"

bind-key ^=     resize-pane -D 2
bind-key ^-     resize-pane -U 2
bind-key -      resize-pane -L 4
bind-key =      resize-pane -R 4
bind-key J      swap-pane -D
bind-key K      swap-pane -U
bind-key x      kill-pane
bind-key r      source-file $HOME/.tmux.conf
bind-key ^Up    set status-position "top"
bind-key ^Down  set status-position "bottom"
bind-key ^Left  set status          "off"
bind-key ^Right set status          "on"

## bar
set-option -g status                   "on"
set-option -g status-bg                "brightyellow"
set-option -g status-justify           "left"
set-option -g status-left-length       "100"
set-option -g status-right-length      "100"

## messages
set-option -g message-style            "fg=brightcyan,bg=red,align=centre"
set-option -g message-command-style    "fg=brightcyan,bg=red,align=centre"

## panes
set-option -g window-status-separator  ""
set-option -g pane-border-style        "fg=brightblack"
set-option -g pane-active-border-style "fg=brightyellow"
set-option -g pane-border-lines        "heavy"
set-option -g pane-scrollbars-style    "fg=yellow,bg=brightblack"
set-option -g pane-scrollbars          "modal"

## active
set-option -g                    \
    window-status-current-format \
    "#[fg=blue,bg=brightmagenta] #I #[fg=green]#W "

## inactive
set-option -g                    \
    window-status-format         \
    "#[fg=red] #I #[fg=yellow]#W "

## right
set-option -g                    \
    status-right                 \
    "#[fg=brightblack,bg=brightred] [ 󰟀  #S ]#(~/.local/scripts/status/tmux.sh unicode)"

## left
set-option -g status-left ""
