set -g prefix ^X
set -g base-index 1
set -g history-limit 5000
set -g renumber-windows on
set -g mouse on
set -g default-terminal "tmux-256color"
set -g set-clipboard on
set -g allow-passthrough on
#set -g status-position top
set -g pane-active-border-style "fg=brightred,bg=default"
set -g pane-border-style "fg=brightblack,bg=default"
set -g status-style "fg=black,bg=brightyellow"
#set -g status-style "fg=brightyellow,bg=default"
set -g status-right-length 200
set -g status-right "#(~/.local/scripts/status/tmux.sh)"
set -g status-right-style "bg=brightred"
set -g status-left-style "bg=brightmagenta"
setw -g window-status-format "#W"
setw -g window-status-current-format "#[bg=brightmagenta]#W "

setw -g mode-keys vi
bind u copy-mode
bind-key -T copy-mode-vi u send-keys -X halfpage-up
bind-key -T copy-mode-vi d send-keys -X halfpage-down
bind-key -T copy-mode-vi k send-keys -X cursor-up
bind-key -T copy-mode-vi j send-keys -X cursor-down
bind-key -T copy-mode-vi y send-keys -X yank
bind-key -T copy-mode-vi v send-keys -X begin-selection

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind - resize-pane -L 4
bind ] resize-pane -D 2
bind [ resize-pane -U 2
bind = resize-pane -R 4
bind J swap-pane -D
bind K swap-pane -U
bind C-j split-window -v
bind C-k split-window -v
bind C-h split-window -h
bind C-l split-window -h
bind x kill-pane
bind r source-file ~/.tmux.conf
