theme = "transpo"

[editor]
line-number = "relative"
scroll-lines = 1
auto-format = false
bufferline = "multiple"
color-modes = true
default-yank-register= "+"

    [editor.cursor-shape]
    insert = "bar"
    normal = "block"
    select = "underline"

    [editor.file-picker]
    hidden = false

    [editor.smart-tab]
    enable = false

    [editor.statusline]
    left = [
        "mode",
        "spinner",
        "file-base-name",
        "file-modification-indicator",
    ]
    right = [
        "diagnostics",
        "position",
        "file-encoding",
        "file-type",
        "total-line-numbers",
    ]
    diagnostics = [
        "warning",
        "error",
    ]
    workspace-diagnostics = [
        "warning",
        "error",
    ]
    separator = "│"
    mode.normal = "NORMAL"
    mode.insert = "INSERT"
    mode.select = "SELECT"

[keys.normal]
X = "extend_line_above" # what it should be by default
H = "goto_previous_buffer"
L = "goto_next_buffer"
C-R = ":reload-all"

    [keys.normal.space]
    l = ":toggle soft-wrap.enable"
