# [[grammar]]
# name = "genexpr"
# source.path = "/Users/wisdmm/.config/helix/tree-sitter-genexpr/genexpr.dylib"

# [[language]]
# name = "genexpr"
# scope = "source.genexpr"
# file-types = ["genexpr"]
# indent = { tab-width = 4, unit = "    " }
# grammar = "genexpr"

[[language]]
name = "scheme"
scope = "source.scheme"
injection-regex = "scheme"
file-types = ["ss", "scm", "sld", "slip"]
shebangs = ["scheme", "guile", "chicken", "slip"]
comment-token = ";"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "html"
scope = "source.html"
file-types = ["html"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "xml"
scope = "source.xml"
file-types = ["xml", "plist", { glob = "fonts.conf" }]
indent = { tab-width = 4, unit = "    " }
block-comment-tokens = { start = "<!--", end = "-->" }

[[language]]
name = "scheme"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "steel-language-server" ]

[language-server.steel-language-server]
command = "steel-language-server"
args = []

[[language]]
name = "c"
scope = "source.c"
file-types = ["h", "c", "cpp", "xpm"]
indent = { tab-width = 4, unit = "    " }

[language-server.clangd]
command = "clangd"
args = ["--enable-config"]

[[language]]
name = "rust"
scope = "source.rs"
file-types = ["rs"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
scope = "source.go"
file-types = ["go"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tmux"
scope = "source.tmux.conf"
file-types = ["tmux.conf", { glob = "*.tmux.conf" } ]
grammar = "bash"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
scope = "source.json"
file-types = [
    "json",
    "jsonc",
    "jsonl",
    "maxdefaults",
    "maxdefines",
    "maxhelp",
    "maxpat",
    "maxpref",
    "maxpresets",
    "maxproto",
    "maxquery",
    "maxswatches",
    "maxtheme",
    "maxsnip",
    "maxsnap",
    "maxstx",
]
indent = { tab-width = 4, unit = "    " }
grammar = "json"


[[language]]
name = "toml"
scope = "source.toml"
file-types = ["toml"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "lua"
scope = "source.lua"
file-types = ["lua"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
scope = "source.bash"
injection-regex = "(shell|bash|zsh|sh|ksh)"
file-types = [
  "sh",
  "bash",
  "ash",
  "dash",
  "ksh",
  "mksh",
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "eclass",
  "ebuild",
  "bazelrc",
  "Renviron",
  "zsh-theme",
  "cshrc",
  "tcshrc",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  { glob = "i3/config" },
  { glob = "sway/config" },
  { glob = "*.tmux.conf" },
  { glob = ".bash_history" },
  { glob = ".bash_login" },
  { glob = ".bash_logout" },
  { glob = ".bash_profile" },
  { glob = "*.bashrc" },
  { glob = ".profile" },
  { glob = ".zshenv" },
  { glob = ".zlogin" },
  { glob = ".zlogout" },
  { glob = ".zprofile" },
  { glob = "*.zshrc" },
  { glob = ".zimrc" },
  { glob = "APKBUILD" },
  { glob = ".bash_aliases" },
  { glob = ".Renviron" },
  { glob = "*.xprofile" },
  { glob = "*.xinitrc" },
  { glob = "*.xsession" },
  { glob = "*.xsessionrc" },
  { glob = ".yashrc" },
  { glob = ".yash_profile" },
  { glob = ".hushlogin" },
]
shebangs = ["sh", "bash", "dash", "zsh", "ksh"]
comment-token = "#"
language-servers = [ "bash-language-server" ]
indent = { tab-width = 4, unit = "    " }
