console_title_template = '{{ .Folder }}'
version = 3

[transient_prompt]
template = '󰜥   '
foreground = 'lightRed'
background = 'transparent'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = '{{.Icon}}'
foreground = 'black'
background = 'lightGreen'
type = 'os'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = '  {{ .Name }}'
foreground = 'black'
background = 'lightYellow'
type = 'shell'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' ram: {{ round .PhysicalPercentUsed .Precision }}%'
foreground = 'black'
background = 'lightBlue'
type = 'sysinfo'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ''
template = ' {{ .FormattedMs }}'
foreground = 'black'
background = 'lightMagenta'
type = 'executiontime'
style = 'diamond'
[blocks.segments.properties]
style = 'roundrock'
threshold = 0.0

[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ''
template = '{{.UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
foreground = 'black'
background = 'lightCyan'
type = 'git'
style = 'diamond'
[blocks.segments.properties]
branch_icon = ' '
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true
fetch_worktree_count = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '╭─'
type = 'text'
style = 'plain'

[[blocks.segments]]
template = '   {{ .CurrentDate | date .Format }} |'
type = 'time'
style = 'plain'
[blocks.segments.properties]
time_format = ' 03:04pm'

[[blocks.segments]]
template = '  '
type = 'root'
style = 'plain'

[[blocks.segments]]
template = ' {{ .Path }}'
type = 'path'
style = 'plain'
[blocks.segments.properties]
folder_icon = ' '
folder_separator_icon = '   '
home_icon = ' '

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '╰─ '
type = 'status'
style = 'plain'
[blocks.segments.properties]
always_enabled = true
