#!/bin/sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                                 \
    external_bar                 all:42:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on             \
    focus_follows_mouse          autoraise      \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    skip_window_focus_animation  off            \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.15           \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Books$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Weather$" manage=off
yabai -m rule --add app="^Replacicon$" manage=off
yabai -m rule --add app="^SoulseekQt$" manage=off
yabai -m rule --add app="^qemu*" manage=off
yabai -m rule --add app="^Zen$" title="^Library$" manage=off
yabai -m rule --add title="^([Ss]ettings|[Pp]references)$" manage=off
yabai -m rule --add title="^([Pp]icture-[Ii]n-[Pp]icture)$" manage=off
