#!/bin/bash

source $HOME/.cache/wal/sketchybar_wal.sh

options=(
    style=round
    width=4.5
    hidpi=on
    active_color=$color7
    inactive_color=$background
    blacklist="XQuartz,xquartz,X11,xeyes,uxnemu"
)

borders "${options[@]}"
