[manager]
marker_copied = {{ fg = "{color10}", bg = "{color10}" }}
marker_cut = {{ fg = "{color14}", bg = "{color14}" }}
marker_marked = {{ fg = "{color12}", bg = "{color12}" }}
marker_selected = {{ fg = "{color13}", bg = "{color13}" }}

cwd = {{ fg = "{color7}" }}
hovered = {{ reversed = true }}
preview_hovered = {{ reversed = true }}

find_keyword = {{ fg = "{color12}", bg = "{color0}" }}
find_position = {{}}

tab_active = {{ reversed = true }}
tab_inactive = {{}}
tab_width = 1

count_copied = {{ fg = "{color0}", bg = "{color5}" }}
count_cut = {{ fg = "{color0}", bg = "{color6}" }}
count_selected = {{ fg = "{color0}", bg = "{color7}" }}

border_symbol = "│"
border_style = {{ fg = "{color15}" }}


[mode]
normal_main = {{ fg = "{color0}", bg = "{color10}" }}
normal_alt = {{ fg = "{color10}", bg = "{color0}" }}
select_main = {{ fg = "{color0}", bg = "{color11}" }}
select_alt = {{ fg = "{color11}", bg = "{color0}" }}
unset_main = {{ fg = "{color0}", bg = "{color12}" }}
unset_alt = {{ fg = "{color12}", bg = "{color0}" }}


[status]
sep_left = {{ open = "", close = "" }}
sep_right = {{ open = "", close = "" }}
overall = {{ fg = "{color13}", bg = "{color0}" }}

progress_label = {{ fg = "{color10}", bg = "{color0}", bold = true }}
progress_normal = {{ fg = "{color10}", bg = "{color0}" }}
progress_error = {{ fg = "{color10}", bg = "{color0}" }}

perm_type = {{ fg = "{color10}" }}
perm_read = {{ fg = "{color11}" }}
perm_write = {{ fg = "{color12}" }}
perm_exec = {{ fg = "{color13}" }}
perm_sep = {{ fg = "{color14}" }}


[pick]
border = {{ fg = "{color5}" }}
active = {{ fg = "{color6}", bold = true }}
inactive = {{}}

[input]
border = {{ fg = "{color5}" }}
title = {{}}
value = {{}}
selected = {{ reversed = true }}

[completion]
border = {{ fg = "{color5}" }}
active = {{ reversed = true }}
inactive = {{}}

[tasks]
border = {{ fg = "{color5}" }}
title = {{}}
hovered = {{ fg = "{color6}" }}

[which]
cols = 2
separator = " - "
separator_style = {{ fg = "{color7}" }}
mask = {{ bg = "{color0}" }}
rest = {{ fg = "{color7}" }}
cand = {{ fg = "{color5}" }}
desc = {{ fg = "{color8}" }}

[help]
on = {{ fg = "{color9}" }}
run = {{ fg = "{color6}" }}
desc = {{}}
hovered = {{ reversed = true, bold = true }}
footer = {{ fg = "{color0}", bg = "{color15}" }}

[notify]
title_info = {{ fg = "{color9}" }}
title_warn = {{ fg = "{color10}" }}
title_error = {{ fg = "{color11}" }}

#[filetype]
#rules = [
#    # images
#    {{ mime = "image/*", fg = "{color9}" }},
#
#    # media
#    {{ mime = "{audio,video}/*", fg = "{color10}" }},
#
#    # archives
#    {{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "{color11}" }},
#
#    # documents
#    {{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "{color12}" }},
#
#    # broken links
#    {{ name = "*", is = "orphan", fg = "{color13}" }},
#
#    # executables
#    {{ name = "*", is = "exec", fg = "{color14}" }},
#
#    # fallback
#    {{ name = "*", fg = "{color15}" }},
#    {{ name = "*/", fg = "{color9}" }},
#]
