require('transparent').setup({
  groups = {
    'CmdlinePopup',
    'CmdlinePopupBorder',
    'CmdlinePopupTitle',
    'Comment',
    'Conditional',
    'Constant',
    'EndOfBuffer',
    'FloatBorder',
    'FloatTitle',
    'Function',
    'Identifier',
    'Keyword',
    'LineNr',
    'NonText',
    'Normal',
    'NormalFloat',
    'NormalNC',
    'Operator',
    'PopupNormal',
    'PopupBorder',
    'PreProc',
    'Repeat',
    'SignColumn',
    'Special',
    'Statement',
    'StatusLine',
    'StatusLineNC',
    'String',
    'Structure',
    'TabLine',
    'Todo',
    'Type',
    'Underlined',
    'VertSplit',

    -- 'NoiceCmdline',
    -- 'NoiceCmdlineBorder',
    -- 'NoiceCmdlinePopup',
    -- 'NoiceCmdlinePopupBorder',
    -- 'NoiceCmdlinePopupIcon',
    -- 'NoiceCmdlinePopupTitle',
    -- 'NoiceCmdlineIcon',
    -- 'NoiceCmdlinePrompt',
    -- 'NoicePopup',
    -- 'NoicePopupBorder',
    -- 'NoiceCmdlinePopupBorderCmdline',
    -- 'NoiceCmdlinePopupBorderSearch',
    -- 'NoicePopupmenu',
    -- 'NoicePopupmenuBorder',
    -- 'NoiceSplit',
    -- 'NoiceSplitBorder',

    -- 'TelescopeNormal',
    -- 'TelescopeBorder',
    -- 'TelescopePromptNormal',
    -- 'TelescopePromptBorder',
    -- 'TelescopePromptTitle',
    -- 'TelescopePreviewNormal',
    -- 'TelescopePreviewBorder',
    -- 'TelescopePreviewTitle',
    -- 'TelescopeResultsNormal',
    -- 'TelescopeResultsBorder',
    -- 'TelescopeResultsTitle',
  },
})
